[project]
name = "gold-miner-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "langchain-ollama>=1.0.1",
    "langgraph>=1.0.8",
    "pandas>=3.0.0",
    "pdfplumber>=0.11.9",
    "pydantic>=2.12.5",
]
